nova_flavors:
- disk: 1
  name: m1.micro
  ram: 256
  vcpus: 1
- disk: 1
  name: m1.tiny
  ram: 512
  vcpus: 1
- disk: 20
  name: m1.small
  ram: 2048
  vcpus: 1
- disk: 40
  name: m1.medium
  ram: 4096
  vcpus: 2
- disk: 80
  name: m1.large
  ram: 8192
  vcpus: 4
- disk: 160
  name: m1.xlarge
  ram: 16384
  vcpus: 8

nova_helm_values:
  pod:
    replicas:
      api_metadata: 1
      osapi: 1
      conductor: 1
      novncproxy: 1
      spiceproxy: 1
  conf:
    nova:
      DEFAULT:
        osapi_compute_workers: 1
        metadata_workers: 1
      conductor:
        workers: 1
      scheduler:
        workers: 1
