# This is a basic workflow to help you get started with Actions

name: Humanz Cloud config CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
    paths-ignore:
      - '.github/**'
    branches: [ "master" ]
    types: [opened, reopened]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Install ansible 
      - name: Install Ansible
        shell: bash
        run: |
          sudo apt update
          sudo apt install -y ansible

      # Runs ansible galaxy for installing cloud config requirement
      - name: Install cloud config requirements
        run: |
          ansible-galaxy collection install -r requirements.yaml

      - name: Install atmosphere dependency
        run: |
          pip install -r ~/.ansible/collections/ansible_collections/vexxhost/atmosphere/requirements.txt

      - name: Decrypt GPG secret.yml
        run: |
          gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.GPG_PASSPHRASE }}" --output inventory/group_vars/all/secrets.yml inventory/group_vars/all/secrets.yml.gpg

      - name: Run cloud config
        run: |
          ansible-playbook -u root -i inventory/hosts.ini playbooks/site.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: false